services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: linkTrace_dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: linkTrace_worker_dev
    command: npm run worker:dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: always
